name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.7
  - pandas
  - scikit-learn
  - jupyter
  - pynrrd
  - matplotlib
  - seaborn
  - pip:
      - alabaster==0.7.12
      - annexremote==1.6.0
      - astor==0.8.1
      - bids-validator==1.9.9
      - boto==2.49.0
      - chardet==4.0.0
      - datalad==0.17.9
      - docopt==0.6.2
      - docutils==0.19
      - fasteners==0.18
      - formulaic==0.3.4
      - freesurfer-stats==1.2.1
      - humanize==4.4.0
      - imagesize==1.4.1
      - importlib-metadata==5.1.0
      - interface-meta==1.3.0
      - iso8601==1.1.0
      - jaraco-classes==3.2.3
      - jeepney==0.8.0
      - jinja2==3.0.3
      - keyring==23.11.0
      - keyrings-alt==4.2.0
      - lxml==5.1.0
      - more-itertools==9.0.0
      - msgpack==1.0.4
      - nilearn==0.10.2
      - num2words==0.5.12
      - patool==1.12
      - platformdirs==2.5.4
      - pybids==0.15.5
      - pygments==2.13.0
      - python-gitlab==3.12.0
      - pyyaml==6.0
      - requests-toolbelt==0.10.1
      - scikit-learn==1.0.2
      - secretstorage==3.3.3
      - simplejson==3.18.0
      - sklearn==0.0.post1
      - snowballstemmer==2.2.0
      - sphinx==5.3.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - sqlalchemy==1.3.24
      - whoosh==2.7.4
      - wrapt==1.14.1
